name: Box64 v0.3.0 for Winlator

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    name: Build Box64 v0.3.0
    runs-on: ubuntu-latest
    timeout-minutes: 60

    env:
      BOX64_COMMIT: 62695ce5c1f74800b5bba57c104cca37eef1a11c
      RELEASE_TAG: BOX64-v0.3.0
      NDK_VERSION: r26b
      API_LEVEL: 31
      BUILD_TYPE: Release

    steps:
      - name: Install build dependencies
        run: |
          sudo apt-get -yqq update
          sudo apt-get -yqq install --no-install-recommends \
            git cmake make ninja-build python3 zstd file curl unzip ca-certificates binutils

      - name: Checkout Box64 at commit 62695ce (v0.3.0)
        uses: actions/checkout@v4
        with:
          repository: ptitSeb/box64
          ref: ${{ env.BOX64_COMMIT }}
          submodules: recursive
          path: box64
          fetch-depth: 1

      - name: Download and setup Android NDK
        run: |
          NDK_BASE="android-ndk-${NDK_VERSION}"
          URL="https://dl.google.com/android/repository/${NDK_BASE}-linux.zip"
          
          curl -fsSL -o ndk.zip "$URL"
          unzip -q ndk.zip
          
          echo "NDK=$PWD/${NDK_BASE}" >> $GITHUB_ENV
          echo "BOX64_COMPILER=$PWD/${NDK_BASE}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android${API_LEVEL}-clang" >> $GITHUB_ENV

      - name: Configure CMake
        run: |
          cd box64
          mkdir -p build && cd build
          cmake .. \
            -G Ninja \
            -DCMAKE_C_COMPILER="${BOX64_COMPILER}" \
            -DANDROID=1 \
            -DARM_DYNAREC=1 \
            -DBAD_SIGNAL=1 \
            -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
            -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
            -DZYDIS3=0 \
            -DSTATICBUILD=0 \
            -DBOX32=0

      - name: Build Box64
        run: cmake --build box64/build -j$(nproc)

      - name: Strip binary
        run: |
          BIN="box64/build/box64"
          STRIP_BIN="${NDK}/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip"
          
          if [[ -x "$STRIP_BIN" ]]; then
            "$STRIP_BIN" --strip-unneeded "$BIN"
          else
            strip --strip-unneeded "$BIN"
          fi
          
          file "$BIN"
          echo "Binary size: $(ls -lh $BIN | awk '{print $5}')"

      - name: Verify Android binary
        run: |
          echo "=== INTERPRETER ==="
          readelf -lW box64/build/box64 | grep interpreter || true
          echo "=== NEEDED LIBS ==="
          readelf -d box64/build/box64 | grep NEEDED || true

      - name: Package WCP
        run: |
          mkdir -p Box64_WCP artifacts
          cp box64/build/box64 Box64_WCP/box64
          chmod +x Box64_WCP/box64
          
          cat > Box64_WCP/profile.json <<'JSON'
          {
            "type": "Box64",
            "versionName": "0.3.0",
            "versionCode": 300,
            "description": "Box64 v0.3.0 for Winlator (Official Release)",
            "files": [
              { "source": "box64", "target": "${bindir}/box64" }
            ]
          }
          JSON
          
          cd Box64_WCP
          tar --zstd --format=gnu --owner=0 --group=0 --numeric-owner --sort=name \
              -cf "../artifacts/box64-v0.3.0.wcp" profile.json box64

      - name: Create/Update Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          cat > /tmp/release_notes.md <<'EOF'
          Box64 v0.3.0 for Winlator
          
          Built from commit: 62695ce (v0.3.0 release, July 9, 2024)
          Official release: https://github.com/ptitSeb/box64/releases/tag/v0.3.0
          
          Build details:
          - Android NDK: r26b
          - API Level: 31
          - Build Type: Release
          EOF
          
          if ! gh release view "${RELEASE_TAG}" --repo "${{ github.repository }}" >/dev/null 2>&1; then
            gh release create "${RELEASE_TAG}" \
              --repo "${{ github.repository }}" \
              --title "Box64 v0.3.0" \
              --notes-file /tmp/release_notes.md
          fi
          
          gh release upload "${RELEASE_TAG}" \
            "./artifacts/box64-v0.3.0.wcp" \
            --repo "${{ github.repository }}" \
            --clobber
